import React from "react";
import { AIBadge } from "./AIBadge";
import { AILoader } from "./AILoader";

interface AICoachCardProps {
  /** The natural coaching text generated by useAICoach. */
  feedback: string;
  /** Whether the AI feedback is currently loading/generating. */
  loading: boolean;
  /** Any error returned by the hook (determines if fallback is active). */
  error: Error | null;
  /** Callback to trigger refresh. */
  onRefresh: () => void;
  /** Whether a hand is being tracked. */
  isTracking: boolean;
}

/**
 * Beautiful Glassmorphism card displaying Guru Nataraja AI coaching feedback.
 * Renders below the traditional rule-based CoachCard on the PracticePage.
 */
export const AICoachCard: React.FC<AICoachCardProps> = ({
  feedback,
  loading,
  error,
  onRefresh,
  isTracking,
}) => {
  const isFallback = error !== null || !feedback;
  const status = isFallback ? "offline" : "active";

  if (!isTracking) {
    return null;
  }

  return (
    <div className="glass-card p-6 border border-surface-700/50 shadow-lg shadow-surface-950/20 animate-fade-in transition-all duration-300">
      {/* Header section with Badge */}
      <div className="flex items-center justify-between gap-4 mb-4">
        <div className="flex items-center gap-2">
          <span className="text-xl shrink-0" role="img" aria-label="Guru AI logo">
            🤖
          </span>
          <h3 className="text-sm font-semibold text-white tracking-wide">
            AI Coach
          </h3>
        </div>
        <AIBadge status={status} />
      </div>

      {/* Body content */}
      <div className="min-h-[80px] flex flex-col justify-between gap-4">
        {loading ? (
          <AILoader />
        ) : (
          <div className="space-y-3">
            <p className="text-sm leading-relaxed text-surface-200 font-sans italic">
              "{feedback}"
            </p>
            {isFallback && (
              <p className="text-[11px] text-surface-500">
                Notice: AI Coach is currently offline. Displaying native rule engine message.
              </p>
            )}
          </div>
        )}

        {/* Action Button Section */}
        <div className="flex items-center justify-between pt-3 border-t border-surface-700/30">
          <span className="text-[10px] text-surface-500 font-mono">
            Model: llama-3.1-8b
          </span>
          <button
            onClick={onRefresh}
            disabled={loading}
            className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-semibold text-primary-400 hover:text-primary-300 disabled:text-surface-600 disabled:pointer-events-none hover:bg-surface-800/40 transition-all duration-200 cursor-pointer"
          >
            <svg
              xmlns="http://www.w3.org/2000/svg"
              width="12"
              height="12"
              viewBox="0 0 24 24"
              fill="none"
              stroke="currentColor"
              strokeWidth="2.5"
              strokeLinecap="round"
              strokeLinejoin="round"
              className={loading ? "animate-spin" : ""}
            >
              <path d="M3 12a9 9 0 0 1 9-9 9.75 9.75 0 0 1 6.74 2.74L21 8" />
              <path d="M21 3v5h-5" />
              <path d="M21 12a9 9 0 0 1-9 9 9.75 9.75 0 0 1-6.74-2.74L3 16" />
              <path d="M3 21v-5h5" />
            </svg>
            Explain Again
          </button>
        </div>
      </div>
    </div>
  );
};
